version: 2.1
executors:
  docker-publisher:
    environment:      
      ALPINE_VER: 3.10.3
      VM_MAJOR_VER: v3.10
      VM_VER: v1.30.3
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            wget http://dl-5.alpinelinux.org/alpine/${VM_MAJOR_VER}/releases/x86_64/alpine-minirootfs-${ALPINE_VER}-x86_64.tar.gz
            docker build --build-arg VM_VER=${VM_VER} --build-arg ALPINE_VER=${ALPINE_VER} -t ${CIRCLE_PROJECT_REPONAME}:${VM_VER} .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar ${CIRCLE_PROJECT_REPONAME}:${VM_VER}
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker tag ${CIRCLE_PROJECT_REPONAME}:${VM_VER} $CIRCLE_PROJECT_REPONAME:latest
            docker push $CIRCLE_PROJECT_REPONAME:latest
            docker push ${CIRCLE_PROJECT_REPONAME}:${VM_VER}

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
